const moment = require('moment-timezone');
const { generateJetLagPlan } = require('./jetLagAlgorithm');

// Mock specific logic
// We need to inspect the 'Adjust' phase cards generated by logic.
// We can simulate a simple trip to trigger generating cards.

// Mock data
const mockTrip = {
    id: 'test-trip',
    from: 'New York',
    to: 'London',
    departDate: '2023-06-01',
    departTime: '18:00',
    arriveDate: '2023-06-02',
    arriveTime: '06:00',
    segments: []
};

function runTest(scenarioName, wakeTime, bedtime) {
    console.log(`\n--- Testing Scenario: ${scenarioName} ---`);
    console.log(`Settings: Wake ${wakeTime}, Bed ${bedtime}`);

    const userSettings = {
        normalWakeTime: wakeTime,
        normalBedtime: bedtime,
        useMelatonin: false,
        useMagnesium: false
    };

    const plan = generateJetLagPlan(mockTrip, [mockTrip], userSettings);
    const adjustCards = plan.phases.adjust.cards;

    // Check Sunlight Title
    const sunCard = adjustCards.find(c => c.id === 'adjust-morning-light-daily');
    if (sunCard) {
        console.log(`[Sunlight] Title: "${sunCard.title}" (Time: ${sunCard.time})`);
    } else {
        console.log(`[Sunlight] NOT FOUND`);
    }

    // Check Caffeine OK
    const caffeineOkCard = adjustCards.find(c => c.id === 'adjust-caffeine-ok');
    if (caffeineOkCard) {
        console.log(`[Caffeine OK] Found: YES. Time details: ${caffeineOkCard.time}`);
    } else {
        console.log(`[Caffeine OK] Found: NO (Hidden as expected due to late wake?)`);
    }

    // Check No Caffeine
    const noCaffeineCard = adjustCards.find(c => c.id === 'adjust-no-caffeine');
    if (noCaffeineCard) {
        console.log(`[No Caffeine] Title: "${noCaffeineCard.title}"`);
        console.log(`[No Caffeine] Time: "${noCaffeineCard.time}"`);
        console.log(`[No Caffeine] DateTime: ${noCaffeineCard.dateTime}`);
    } else {
        console.log(`[No Caffeine] NOT FOUND`);
    }
}

// 1. Normal (Wake 07:00, Bed 23:00) -> Cutoff 14:00 (2 PM)
// expect: "Caffeine OK 7am - 2pm", "No Caffeine After 2:00 PM"
runTest('Normal', '07:00', '23:00');

// 2. Late Wake (Wake 13:00, Bed 23:00) -> Cutoff 14:00 (2 PM)
// expect: "Seek Sunlight" (not Morning), "Caffeine OK 1pm - 2pm" (Short), "No Caffeine After 2:00 PM"
runTest('Late Wake (Short Window)', '13:00', '23:00');

// 3. Very Late Wake (Wake 15:00, Bed 23:00) -> Cutoff 14:00 (2 PM)
// expect: "Seek Sunlight", NO Caffeine OK card, "No Caffeine Since waking"
runTest('Very Late Wake (Past Cutoff)', '15:00', '23:00');

// 4. Night Owl (Wake 12:00, Bed 02:00) -> Cutoff 17:00 (5 PM)
// expect: "Seek Sunlight", "Caffeine OK 12pm - 5pm", "No Caffeine After 5:00 PM"
runTest('Night Owl', '12:00', '02:00');
